services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/userdb
      - PORT=9000
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
